---
title: "about"
author: "Gabe Cederberg"
date: "4/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Welcome to my project!


*The goal of this project is to explore whether counties that lean Republican or Democrat responded differently to covid-19 shutdown orders.*


### Cuebiq

The first dataset is a compilation of the daily product mix sales reports from 76 different days over a 3-month period. The files include the date of a sale, the location of the sale within the restaurant (i.e. main restaurant, bar, lounge, event), and the name, category, identification number, quantity, and price of each item sold on that particular day. 

I compiled the single, tidied spreadsheet by writing a code that reads in the 76 csv files and binds them together. Then I removed all non-essential rows from the data frame (i.e. location totals) by tactically removing all rows without an identification number. Then I programmed so that the location and category variables would each replicate into all rows below them until it reached another location or category. This assigned the correct location and category type to all of the items. Then I fixed the column names and data types, including changing the file names into the date column. Then, because I wanted to distinguish between days that had an event and those that didn't (because events could distort sales numbers within the other locations), I create a new variable and merged the dataset to a list of the days with events to create a dummy variable for event days. Lastly, because I wanted to graph trends by weekday and month, I created additional variables to state the day of the week and month of a particular date.  


### Weather Dataset

Beyond the internal operations of the restaurant, I am also curious about how external factors, like weather, can affect the business' performance over this time period. To do this, I downloaded daily weather summaries for the Boston area spanning the three-month restaurant sales period from the US NOAA's National Centers for Environmental Information. This dataset includes measures like the max, min, and average temperatures, the amount of precipitation, the amount of snow, and various wind speed and wind direction measures. To operationalize this dataset, I merged it with the original restaurant dataset using the date columns. 

This has allowed me to run regressions between restaurant sales and various weather factors to test whether different weather conditions affect the restaurant's sales in different ways. 


### A Quick Caveat

I have not been able to ensure that the data is immune to deanonymization. Therefore, I have chosen to not push my data files to GitHub at this  moment. I am going to speak to the course heads to determine what I can do to ensure I follow through on the non-disclosure promises that I gave to the restaurant. 


## Contact
Hey! I'm Gabe Cederberg, a Junior at Harvard College studying Government, with a secondary in Economics. I can be reached at gabrielcederberg@college.harvard.edu.

This project is being created for my Gov 1005 final project. My code can be accessed from this github repo: 

https://github.com/GabeCeder/FinalProject
