---
title: "analysis"
author: "Gabe Cederberg"
date: "4/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Loading the important packages.

library(tidyverse)
library(dplyr)
library(readr)
library(fivethirtyeight)
library(janitor)
library(ggthemes)
library(gt)
library(reprex)
library(magrittr)
library(stringr)
library(haven)
library(infer)
library(readxl)
library(viridis)  
library(RCurl)
library(gifski)
library(gganimate)

```

# {.tabset}

## First analysis

```{r, echo = FALSE, warning = FALSE}
# Loading in data from NYT. 

library(RCurl)
county_text <- getURL("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")
county_a <- read_csv(county_text)

state_text <- getURL("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")
state_a <- read_csv(state_text)

partisanship_text <- getURL("https://raw.githubusercontent.com/MEDSL/2018-elections-unoffical/master/election-context-2018.csv")
partisanship <- read_csv(partisanship_text,
                         col_types = cols(
                fips = col_character()))

partisanship

partisanship %>% 
  filter(state == "Missouri")

merged <- county_a %>% 
  left_join(partisanship, by = c("county", "state"))

a <- merged %>% 
  mutate(dem = clinton16 / (trump16 + clinton16)) %>% 
  filter(date == "2020-03-30" &
           !is.na(clinton16))

# merged %>% 
#  filter(is.na(trump16))
                
partisanship

ggplot(a, aes(cases, dem)) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_y_discrete(limits = 0:1,
                   breaks = c(0, 0.25, 0.5, 0.75, 1), 
                   label = c("0%", "25%", "50%", "75%", "100%")) +
  scale_x_discrete(limits = 0:10000,
                   breaks = c(0, 2500, 5000, 7500, 10000), 
                   label = c("0", "2,500", "5,000", "7,500", "10,000")) +
  theme_classic() +
  labs(x = "Cases", 
       y = "Percent Democratic 2016", 
        title = "Cases in Each US County by Partisan Leaning", 
        subtitle = "Counties that lean Democratic tend to have more cases") + ylim(0, 1)
  
ggsave("secondplot.png", 
       plot = last_plot(), path = "FinalProjectV1.0/")
```


```{r, echo = FALSE}
county <- county_a %>% 
  mutate(region = case_when(state == "Connecticut" |
                           state == "Maine" |
                           state == "Massachusetts" |
                           state == "New Hampshire" |
                           state == "Rhode Island" |
                           state == "Vermont" |
                           state == "New Jersey" |
                           state == "New York" |
                           state == "Pennsylvania" ~ "Northeast",
                           
                           state == "Illinois" |
                             state == "Indiana" |
                             state == "Michigan" |
                             state == "Ohio" |
                             state == "Wisconsin" |
                             state == "Iowa" |
                             state == "Kansas" |
                             state == "Minnesota" |
                             state == "Missouri" |
                             state == "Nebraska" |
                             state == "North Dakota" |
                             state == "South Dakota" ~ "Midwest",
                           
                             state == "Delaware" |
                             state == "Florida" |
                             state == "Georgia" |
                             state == "Maryland" |
                             state == "North Carolina" |
                             state == "South Carolina" |
                             state == "Virginia" |
                             state == "District of Columbia" |
                             state == "West Virginia" |
                             state == "Alabama" |
                             state == "Kentucky" |
                             state == "Mississippi" |
                             state == "Tennessee" |
                             state == "Arkansas" |
                             state == "Louisiana" |
                             state == "Oklahoma" |
                             state == "Texas" ~ "South",
                           
                             state == "Arizona" |
                             state == "Colorado" |
                             state == "Idaho" |
                             state == "Montana" |
                             state == "Nevada" |
                             state == "New Mexico" |
                             state == "Utah" |
                             state == "Wyoming" |
                             state == "Alaska" |
                             state == "California" |
                             state == "Hawaii" |
                             state == "Oregon" |
                             state == "Washington" ~ "West",
                           
                            state == "Northern Mariana Islands" | 
                             state == "Puerto Rico" | 
                             state == "Guam" | 
                             state == "Virgin Islands" ~ "Other" ))

state <- state_a %>% 
  mutate(region = case_when(state == "Connecticut" |
                           state == "Maine" |
                           state == "Massachusetts" |
                           state == "New Hampshire" |
                           state == "Rhode Island" |
                           state == "Vermont" |
                           state == "New Jersey" |
                           state == "New York" |
                           state == "Pennsylvania" ~ "Northeast",
                           
                           state == "Illinois" |
                             state == "Indiana" |
                             state == "Michigan" |
                             state == "Ohio" |
                             state == "Wisconsin" |
                             state == "Iowa" |
                             state == "Kansas" |
                             state == "Minnesota" |
                             state == "Missouri" |
                             state == "Nebraska" |
                             state == "North Dakota" |
                             state == "South Dakota" ~ "Midwest",
                           
                             state == "Delaware" |
                             state == "Florida" |
                             state == "Georgia" |
                             state == "Maryland" |
                             state == "North Carolina" |
                             state == "South Carolina" |
                             state == "Virginia" |
                             state == "District of Columbia" |
                             state == "West Virginia" |
                             state == "Alabama" |
                             state == "Kentucky" |
                             state == "Mississippi" |
                             state == "Tennessee" |
                             state == "Arkansas" |
                             state == "Louisiana" |
                             state == "Oklahoma" |
                             state == "Texas" ~ "South",
                           
                             state == "Arizona" |
                             state == "Colorado" |
                             state == "Idaho" |
                             state == "Montana" |
                             state == "Nevada" |
                             state == "New Mexico" |
                             state == "Utah" |
                             state == "Wyoming" |
                             state == "Alaska" |
                             state == "California" |
                             state == "Hawaii" |
                             state == "Oregon" |
                             state == "Washington" ~ "West",
                           
                            state == "Northern Mariana Islands" | 
                             state == "Puerto Rico" | 
                             state == "Guam" | 
                             state == "Virgin Islands" ~ "Other" ))

only_states <- state %>% 
  filter(region != "Other" &
           date > "2020-03-15")
```


```{r, echo = FALSE}

ggplot(only_states, aes(date, y = cases, color = state)) + 
  geom_line() +
  facet_wrap(~ region) +
#  transition_reveal(date) +
  theme_classic() +
  labs(x = "Date", 
       y = "Total Number of Cases", 
        title = "Cases by State Since March 16th", 
        subtitle = "States in the Northeast region showing rapid increase in cases") +
  theme(
        legend.position = "none",
        panel.background = element_blank()) 
      #  axis.line = element_line(color = "black"),
      #  axis.text.x = element_text(angle = 45, hjust = 1))

ggsave("firstplot.png", 
       plot = last_plot(), path = "FinalProjectV1.0/")

```


```{r, include = FALSE}
library(tidycensus)


pop <- get_decennial(geography = "county",
                       variables = "P001001",
                       year = 2010,
                       output = "wide")


v10 <- load_variables(2010, "sf1", cache = TRUE)
```

