---
title: "countydata"
author: "Gabe Cederberg"
date: "4/24/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

options(tigris_use_cache = TRUE)

# Loading the important packages.

library(readr)
library(janitor)
library(ggthemes)
library(haven)
library(infer)
library(readxl)
library(viridis)  
library(gganimate)
library(tidycensus)
library(RCurl)
library(tidyverse)


```

# {.tabset}

## First analysis

```{r, echo = FALSE, warning = FALSE, cache = TRUE}
# Loading in county data from NYT. 

county_text <- getURL("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")
county <- read_csv(county_text) %>% 
  select(county, state, fips, cases) %>% 
    group_by(county, state) %>% 
  mutate(max_case = max(cases)) %>%   
  filter(cases == max_case) %>% 
  ungroup() %>% 
  distinct()

# Loading data from Tidycensus

counties <- get_acs(geography = "county",
                  variables = c(pop = "B01003_001"), 
                  year = 2018,
                  geometry = TRUE) %>% 
  clean_names() %>% 
   select(geoid, 
          name, 
          "pop" = estimate,
          geometry) %>% 
  separate(col = name, c("county", "state"), sep = ", ")

# Merging the datasets

merged <- counties %>% 
  left_join(county, by = c("geoid" = "fips"))  %>% 
      select(geoid, 
         "county" = county.x,
         "state" = state.x, 
         pop,
         cases, 
         geometry) %>% 
  mutate(cases_per_thousand = (cases / pop) * 1000)

# Saving to an RDS file for the Shiny App

saveRDS(merged, file = "FinalProjectV1.0/county_map_data.rds")
 
```



```{r}
# Testing out the graph

merged %>% 
    ggplot(aes(fill = max_case, color = max_case)) +
  geom_sf(data = merged) +
   scale_fill_viridis_c(direction = -1) +
   scale_color_viridis_c(direction = -1) +
  labs(title = "Cases by County",
       caption = "Source: The New York Times and the American Community Survey 2014-2018",
       color = "Total Number of Cases") +
  theme(fill.position = element_blank()) +
  theme_void()

# partisanship_text <- getURL("https://raw.githubusercontent.com/MEDSL/2018-elections-unoffical/master/election-context-2018.csv")
# partisanship <- read_csv(partisanship_text,
#                          col_types = cols(
#                 fips = col_character()))
# 
# partial_merged <- county %>% 
#   left_join(partisanship, by = c("county", "state"))

```
