---
title: "countydata"
author: "Gabe Cederberg"
date: "4/24/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

options(tigris_use_cache = TRUE)

# Loading the important packages.

library(tidyverse)
library(dplyr)
library(readr)
library(fivethirtyeight)
library(janitor)
library(ggthemes)
library(gt)
library(reprex)
library(magrittr)
library(stringr)
library(haven)
library(infer)
library(readxl)
library(viridis)  
library(RCurl)
library(gifski)
library(gganimate)
library(tidycensus)

```

# {.tabset}

## First analysis

```{r, echo = FALSE, warning = FALSE, cache = TRUE}
# Loading in state data from NYT. 

county_text <- getURL("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")
county_a <- read_csv(county_text)

county <- county_a %>% 
  mutate(region = case_when(state == "Connecticut" |
                           state == "Maine" |
                           state == "Massachusetts" |
                           state == "New Hampshire" |
                           state == "Rhode Island" |
                           state == "Vermont" |
                           state == "New Jersey" |
                           state == "New York" |
                           state == "Pennsylvania" ~ "Northeast",
                           
                           state == "Illinois" |
                             state == "Indiana" |
                             state == "Michigan" |
                             state == "Ohio" |
                             state == "Wisconsin" |
                             state == "Iowa" |
                             state == "Kansas" |
                             state == "Minnesota" |
                             state == "Missouri" |
                             state == "Nebraska" |
                             state == "North Dakota" |
                             state == "South Dakota" ~ "Midwest",
                           
                             state == "Delaware" |
                             state == "Florida" |
                             state == "Georgia" |
                             state == "Maryland" |
                             state == "North Carolina" |
                             state == "South Carolina" |
                             state == "Virginia" |
                             state == "District of Columbia" |
                             state == "West Virginia" |
                             state == "Alabama" |
                             state == "Kentucky" |
                             state == "Mississippi" |
                             state == "Tennessee" |
                             state == "Arkansas" |
                             state == "Louisiana" |
                             state == "Oklahoma" |
                             state == "Texas" ~ "South",
                           
                             state == "Arizona" |
                             state == "Colorado" |
                             state == "Idaho" |
                             state == "Montana" |
                             state == "Nevada" |
                             state == "New Mexico" |
                             state == "Utah" |
                             state == "Wyoming" |
                             state == "Alaska" |
                             state == "California" |
                             state == "Hawaii" |
                             state == "Oregon" |
                             state == "Washington" ~ "West",
                           
                            state == "Northern Mariana Islands" | 
                             state == "Puerto Rico" | 
                             state == "Guam" | 
                             state == "Virgin Islands" ~ "Other" ))

partisanship_text <- getURL("https://raw.githubusercontent.com/MEDSL/2018-elections-unoffical/master/election-context-2018.csv")
partisanship <- read_csv(partisanship_text,
                         col_types = cols(
                fips = col_character()))

partial_merged <- county %>% 
  left_join(partisanship, by = c("county", "state"))

counties <- get_acs(geography = "county",
                  variables = c(pop = "B00001_001"), 
                  year = 2018,
          #        state = c("MN", "NY"),
           #       county = "Ramsey",
                  geometry = TRUE) %>% 
  clean_names() %>% 
   select(geoid, 
          name, 
          "pop" = estimate,
          geometry) %>% 
  separate(col = name, c("county", "state"), sep = ", ")

merged <- counties %>% 
  left_join(partial_merged, by = c("geoid" = "fips.x")) %>% 
  select(geoid, 
         "county" = county.x,
         "state" = state.x, 
         "pop" = total_population,
         date, 
         cases, 
         deaths, 
         region,
         geometry) %>% 
  mutate(cases_per_capita = cases / pop,
         deaths_per_capita = deaths / pop) %>% 
  group_by(county, state) %>% 
  mutate(max_case = max(cases),
         max_death = max(deaths)) %>% 
  ungroup() %>% 
  group_by(state)

saveRDS(merged, file = "county_data.rds")
# Restore the object
# readRDS(file = "my_data.rds")
```


```{r}

merged %>% 
    ggplot(aes(fill = max_case, color = max_case)) +
  geom_sf(data = merged) +
   scale_fill_viridis_c(direction = -1) +
   scale_color_viridis_c(direction = -1) +
  labs(title = "Cases by County",
       caption = "Source: The New York Times and the American Community Survey 2014-2018",
       color = "Total Number of Cases") +
  theme(fill.position = element_blank()) +
  theme_void()

```
