---
title: "regression_counties"
author: "Gabe Cederberg"
date: "4/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Loading necessary packages

library(tidyverse)
library(tidycensus)
library(readxl)
library(stargazer)
library(broom)

# Import population density data

raw_density <- read_excel("raw-data/county_density.xlsx") %>% 
  select(county = "county",
         state = "state",
         pop_per_sq_mile = "popsqmile")

```

```{r nj, include=FALSE}

# Reading in the New Jersey partisanship data. 

partisanship_nj <- read_csv("https://raw.githubusercontent.com/MEDSL/2018-elections-unoffical/master/election-context-2018.csv",
                         col_types = cols(
                           fips = col_character())) %>% 
  filter(state == "New Jersey") %>% 
  mutate(pct_dem = clinton16/(trump16 + clinton16)) %>% 
  select(state, county, pct_dem, rural_pct, median_hh_inc, total_population, age65andolder_pct, lesshs_pct)

# Reading in the covid-19 data for New Jersey. 

county_nj <- read_csv("raw-data/counties.csv") %>% 
  filter(state == "New Jersey",
         date == "2020-04-03")

density_nj <- raw_density %>% 
  filter(state == "New Jersey")

nj106 <- read_csv("raw-data/NJ106.csv")
nj330 <- read_csv("raw-data/NJ330.csv")
nj <- left_join(nj106, nj330, by = "county", .x = "1.06nj", .y = "3.30nj")

joined_nj <- left_join(nj, county_nj, by = "county") %>% 
  left_join(., partisanship_nj, by = "county") %>% 
  left_join(., density_nj, by = "county") %>% 
  mutate(deltaindex = Index.y - Index.x)

base_nj <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + pop_per_sq_mile, data=joined_nj)
# summary(base_nj)

add_edu_nj <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + pop_per_sq_mile + lesshs_pct, data=joined_nj)
# summary(add_edu_nj)

add_elder_nj <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + pop_per_sq_mile + age65andolder_pct, data=joined_nj)
# summary(add_elder_nj)

total_nj <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + pop_per_sq_mile + age65andolder_pct + lesshs_pct, data=joined_nj)
summary(total_nj)

```

```{r ny, include=FALSE}

partisanship_ny <- read_csv("https://raw.githubusercontent.com/MEDSL/2018-elections-unoffical/master/election-context-2018.csv",
                         col_types = cols(
                           fips = col_character())) %>% 
  filter(state == "New York") %>% 
  mutate(pct_dem = clinton16/(trump16 + clinton16)) %>% 
  select(state, county, pct_dem, rural_pct, median_hh_inc, total_population, age65andolder_pct, lesshs_pct)

county_ny <- read_csv("raw-data/counties.csv") %>% 
  filter(state == "New York",
         date == "2020-04-03")

density_ny <- raw_density %>% 
  filter(state == "New York")

ny106 <- read_csv("raw-data/NY106.csv") %>% 
  mutate(state = "New York",
         date = "1/06/20")
ny330 <- read_csv("raw-data/NY330.csv") %>% 
  mutate(state = "New York",
         date = "3/30/20")

ny <- left_join(ny106, ny330, by = "county", .x = "1.06ny", .y = "3.30ny")

joined_ny <- left_join(ny, county_ny, by = "county") %>% 
  left_join(., partisanship_ny, by = "county") %>% 
  left_join(., density_ny, by = "county") %>% 
  mutate(deltaindex = Index.y - Index.x)

base_ny <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + pop_per_sq_mile, data=joined_ny)
# summary(base_ny)

add_edu_ny <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + pop_per_sq_mile + lesshs_pct, data=joined_ny)
# summary(add_edu_ny)

add_elder_ny <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + pop_per_sq_mile + age65andolder_pct, data=joined_ny)
# summary(add_elder_ny)

total_ny <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + pop_per_sq_mile + age65andolder_pct + lesshs_pct, data=joined_ny)
summary(total_ny)
```

```{r ct, include=FALSE}

partisanship_ct <- read_csv("https://raw.githubusercontent.com/MEDSL/2018-elections-unoffical/master/election-context-2018.csv",
                         col_types = cols(
                           fips = col_character())) %>% 
  filter(state == "Connecticut") %>% 
  mutate(pct_dem = clinton16/(trump16 + clinton16)) %>% 
  select(state, county, pct_dem, rural_pct, median_hh_inc, total_population, age65andolder_pct, lesshs_pct)

county_ct <- read_csv("raw-data/counties.csv") %>% 
  filter(state == "Connecticut",
         date == "2020-04-03")

density_ct <- raw_density %>% 
  filter(state == "Connecticut")

ct106 <- read_csv("raw-data/CT106.csv") %>% 
  mutate(state = "Connecticut",
         date = "1/06/20")
ct330 <- read_csv("raw-data/CT330.csv") %>% 
  mutate(state = "Connecticut",
         date = "3/30/20")

ct <- left_join(ct106, ct330, by = "county", .x = "1.06ct", .y = "3.30ct")

joined_ct <- left_join(ct, county_ct, by = "county") %>% 
  left_join(., partisanship_ct, by = "county") %>% 
  left_join(., density_ct, by = "county") %>% 
  mutate(deltaindex = Index.y - Index.x)

base_ct <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + pop_per_sq_mile, data=joined_ct)
# summary(base_ct)

add_edu_ct <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + pop_per_sq_mile + lesshs_pct, data=joined_ct)
# summary(add_edu_ct)

add_elder_ct <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + pop_per_sq_mile + age65andolder_pct, data=joined_ct)
# summary(add_elder_ct)

minus_density_ct <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + lesshs_pct + age65andolder_pct, data=joined_ct)
# summary(minus_density_ct)

total_ct <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + pop_per_sq_mile + age65andolder_pct + lesshs_pct, data=joined_ct)
summary(total_ct)
```

```{r both, include=FALSE}
joined_both <- rbind(joined_ny, joined_nj) %>% 
  rbind(., joined_ct)

joined_both <- joined_both %>% 
  mutate(cases_per_thousand = cases / 1000,
         median_hh_inc_k = median_hh_inc / 1000,
         pop_k_per_sq_mile = pop_per_sq_mile / 1000)

base_both <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + pop_per_sq_mile, data=joined_both)
# summary(base_both)

add_edu_both <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + pop_per_sq_mile + lesshs_pct, data=joined_both)
# summary(add_edu_both)

add_elder_both <- lm(deltaindex ~ cases + pct_dem + median_hh_inc + pop_per_sq_mile + age65andolder_pct, data=joined_both)
# summary(add_elder_both)

total_both <- lm(deltaindex ~ cases_per_thousand + pct_dem + median_hh_inc_k + pop_k_per_sq_mile + age65andolder_pct + lesshs_pct, data = joined_both)

summary(total_both)
```


```{r both_polt, include= TRUE}
stargazer(total_both, 
          title="Regression Results", 
          align=TRUE, 
          dep.var.labels=c("Change in Mobility Index"),
          covariate.labels=c("Cases of Covid-19 (Thousands)",
                           "Percent Democratic Vote Share",
                           "Median Household Income (Thousands of dollars)",
                           "Population per Square Mile (Thousands)",
                           "Percent of Population 65 and Older",
                           "Percent of Population without High School Degree",
                           "Constant"),
          type = 'html', 
          out = "FinalProjectV1.0/total_both.html")

```

```{r regression_figures}

ggplot(joined_both, aes(pct_dem, deltaindex)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme_classic() +
  labs(x = "Democratic Percent of 2016 Vote Share", 
       y = "Change in Mobility Index", 
        title = "County Mobility Index Change by Partisan Leaning", 
        subtitle = "Mobility index change from the week of January 6 to March 30") +
  theme(
        legend.position = "none",
        panel.background = element_blank()) 


```