---
title: "sip_regressions"
author: "Gabe Cederberg"
date: "4/28/2020"
output: html_document
---

```{r setup, include=FALSE}
# Loading packages

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidycensus)
library(readxl)
library(stargazer)
library(janitor)

```

```{r covid_cases, echo = FALSE}
# Loading case dataset

cases <- read_csv("datasets/counties.csv",
                  col_types = cols(
                      date = col_date(format = "%m/%d/%y"),
                      county = col_character(),
                      state = col_character(),
                      fips = col_character(),
                      cases = col_double(),
                      deaths = col_double())) %>% 
            filter(date == "2020-04-03")

```


```{r mobility, echo = FALSE}
# Loading mobility dataset

mobility <- read_excel("datasets/merged.xlsx") 

```


```{r partisanship, echo = FALSE}
# Loading partisanship dataset

partisanship <- read_csv("https://raw.githubusercontent.com/MEDSL/2018-elections-unoffical/master/election-context-2018.csv",
                         col_types = cols(
                           fips = col_character())) %>% 
        mutate(pct_dem = clinton16/(trump16 + clinton16)) %>% 
        select(state, county, pct_dem, rural_pct, 
               median_hh_inc, total_population, 
               age65andolder_pct, lesshs_pct)
```

```{r density, echo = FALSE}
# Loading density dataset

density <- read_csv("datasets/county_density.csv",
                    col_types = cols(
                        County = col_character(),
                        State = col_character(),
                        `FIPS Code` = col_character(),
                        Population = col_double(),
                        Area = col_double(),
                        Density = col_double())) %>% 
  clean_names()

density$county <- gsub(" County", "", density$county)

```


```{r joining, echo = FALSE}
# Joining datasets and mutating necessary variables

joined <- mobility %>% 
  left_join(cases, by = c("county", "state")) %>% 
  left_join(partisanship, by = c("county", "state")) %>% 
  left_join(density, by = c("county", "state")) 

joined$cases[is.na(joined$cases)] <- 0

joined$deaths[is.na(joined$deaths)] <- 0

clean <- joined %>% 
  mutate(delta_sip = march * 100 - jan * 100,
         pct_dem = pct_dem * 100,
         cases_per_thousand = cases / 1000,
         median_hh_inc_k = median_hh_inc / 1000,
         pop_k_per_sq_mile = density / 1000)

```


```{r regressions, echo = FALSE}
# Running the regression models

model_1 <- lm(delta_sip ~ cases_per_thousand + pct_dem + median_hh_inc_k + pop_k_per_sq_mile + age65andolder_pct + lesshs_pct, data = clean)
summary(model_1)

model_2 <- lm(delta_sip ~ cases_per_thousand + pct_dem + median_hh_inc_k + pop_k_per_sq_mile + age65andolder_pct + lesshs_pct + dem_gov, data = clean)
summary(model_2)

model_3 <- lm(scale(delta_sip) ~ scale(cases_per_thousand) + scale(pct_dem) + scale(median_hh_inc_k) + scale(pop_k_per_sq_mile) + scale(age65andolder_pct) + scale(lesshs_pct) + dem_gov, data = clean)
summary(model_3)

# Saving the filespace for the Shiny App

saveRDS(clean, file = "FinalProjectV1.0/county_sip_data.rds")

```

```{r, include = FALSE}
# Calculating the standardized effects of pct_dem and cases_per_thousand

summary(clean)


pct_dem_sd <- clean$pct_dem
sd(pct_dem_sd)

delta_sip_sd <- clean$delta_sip
sd(delta_sip_sd)

cases_per_thousand_sd <- clean$cases_per_thousand
sd(cases_per_thousand_sd)


delta_sip_sd <- clean$delta_sip
sd(delta_sip_sd)

0.29224 * 6.33982

0.17295 * 6.33982

clean
```

```{r}
# Creating html regression output

model_2 <- lm(delta_sip ~ cases_per_thousand + pct_dem + median_hh_inc_k + pop_k_per_sq_mile + age65andolder_pct + lesshs_pct + dem_gov, data = clean)
summary(model_2)

stargazer(model_2, 
          title = "Regression Results", 
          align = TRUE, 
          dep.var.labels = c("Change in Percent of People Staying at Home"),
          covariate.labels = c("Cases of Covid-19 (Thousands)",
                           "Percent Democratic Vote Share",
                           "Median Household Income (Thousands of dollars)",
                           "Population per Square Mile (Thousands)",
                           "Percent of Population 65 and Older",
                           "Percent of Population without High School Degree",
                           "Democratic Governor (1 or 0)",
                           "Constant"),
          type = 'html', 
          out = "FinalProjectV1.0/clean.html")

```

```{r}
# Creating html standardized regression output

model_3 <- lm(scale(delta_sip) ~ scale(cases_per_thousand) + scale(pct_dem) + scale(median_hh_inc_k) + scale(pop_k_per_sq_mile) + scale(age65andolder_pct) + scale(lesshs_pct) + dem_gov, data = clean)
summary(model_3)

stargazer(model_3, 
          title = "Standardized Regression Results", 
          align = TRUE, 
          dep.var.labels = c("Std. Dev. of Change in Percent of People Staying at Home"),
          covariate.labels = c("Cases of Covid-19 (Thousands)",
                           "Percent Democratic Vote Share",
                           "Median Household Income (Thousands of dollars)",
                           "Population per Square Mile (Thousands)",
                           "Percent of Population 65 and Older",
                           "Percent of Population without High School Degree",
                           "Democratic Governor (1 or 0)",
                           "Constant"),
          type = 'html', 
          out = "FinalProjectV1.0/clean_standard.html")

```
